apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: notification-twitter-id
spec:
  destination:
    name: notification-service
  precedence: 2
  match:
    request:
      headers:
        portfolio:
          exact: "John"
  route:
  - labels:
      version: twitter
